name: Tests
on: push
jobs:
  test:
    name: Run tests and linting
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Tests
        run: pipenv run pytest
      - name: Coveralls
        run: pipenv run coveralls
  linting:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Flake8
        run: pipenv run flake8 .
      - name: isort
        run: pipenv run isort . --diff
      - name: bandit
        run: pipenv run bandit asaps